learn-dbt:
  outputs:
    dev:
      account: nr96745.ap-south-1.aws
      client_session_keep_alive: false
      database: analytics
      password: Applmgr@11
      role: ACCOUNTADMIN
      schema: dbt
      threads: 1
      type: snowflake
      user: vinssitsol
      warehouse: transform_wh
  target: dev
